baseurl = "vibrant-ritchie-fd2063.netlify.com"
languageCode = "en-us"
title = "Stockholm Syndrome"
theme = "cocoa-hugo-theme"
builddrafts = true
canonifyurls = true
enableEmoji = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Sol Vitkin"
#disqusshortname = "datascienceish"
googleAnalytics = "UA-123-45"
pluralizelisttitles = false
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]


[permalinks]
blog = "/blog/:slug/"


[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"


[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "A data blog by Sol Vitkin"
faviconfile = "img/leaf.ico"
highlightjs = true
# options for highlight.js (version, additional languages, and theme)
highlightjsVersion = "9.11.0"
highlightjsCDN = "https://cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "python"]
highlightjsTheme = "github"
progressively = true
latestpostcount = 5
github = "//github.com/svitkin"
email = "svitkin@u.rochester.edu"
linkedin = "//linkedin.com/in/sol-vitkin-351237114/"
posts_navigation = true
avatar = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
noshowreadtime = true
selfintro = ""